### ISSUE TITLE
Review literature review chapter

### ISSUE THREAD

**Issue by jbae11** [jbae11/master_thesis#1]
Please review the literature review chapter in [this tag](https://github.com/jbae11/master_thesis/tree/lit_review_d1).

Please let me know about all concerns / ideas / opinions you have. Thank you!

**Comment by katyhuff** [comment]
Honestly, I am surprised that you feel this is ready. I did not expect this chapter at this point in your work. I expect you to be ready for review of your masters chapters in summer 2018 at the earliest. In my opinion, this chapter is not at all ready for review. It is rife with grammatical errors and reads as a cursory list of papers rather than a review of the state of the art in the literature. Please take time to read well-cited literature review articles in journals to understand the "literature review genre". Additionally, please read at least a few (good) masters thesis documents to get an idea of the "masters thesis" genre.

Unrelated: this masters thesis is out of order and has no heading for results. The literature review is not supposed to be the 4th chapter in a thesis. It should be part of the Background chapter. Relatedly, the Background chapter typically follows the introduction (though occasionally these are combined).

I am closing this issue. Feel free to set up a meeting with me to discuss.

**Comment by jbae11** [comment]
yikes, sorry for the miscommunication. My goal wasn't to say that this would be the chapter on the thesis, but rather to let you know of the preliminary results of the brief literature review. I wholeheartedly agree about the writing and it not being coherent.  I plan to structure it better (with additional reading) after fully defining the thesis topic. Preferably after the Quals, if that is okay with you.

**Comment by katyhuff** [comment]
I see. In that case, I'm sorry for being so harsh. I have now read it. Much work remains, but you're on the right track. Of course, I hope you will  put this down and focus on quals (I thought we agreed during our meeting that you were going to focus on quals at this point anyway?). There is nothing at all urgent about this task. Quals are urgent.

**Comment by jbae11** [comment]
Will do! Again thank you for your time and effort. Sorry for the mixup again, I just wanted to let you know where I am with the thesis preparation before I wander off to finals + qual land. I guess asking for a review was not an appropriate way, though.

**Comment by katyhuff** [comment]
I just misunderstood. We're both learning. Thanks.
