### ISSUE TITLE
Huff review round 3

### ISSUE THREAD

**Issue by jbae11** [jbae11/master_thesis#6]
@katyhuff 
All comments have been reflected from round 2 and the chapters are finished up until the conclusion chapter. Additional proofreading has been done to (hopefully) better the paper. Please let me know what you think. Thank you.

[pdf](https://github.com/jbae11/master_thesis/blob/transition/main.pdf)

**Comment by jbae11** [comment]
I apologize for the subpar iteration. I read the entire thing once more to catch more errors. Thank you.

[pdf](https://github.com/jbae11/master_thesis/blob/transition/main.pdf)

**Comment by katyhuff** [comment]
(no need to apologize)
Since I don't see anything here regarding comments that you didn't agree with or suggested changes that you implement, should I assume that you agreed with everything? I'll just reiterate that if you don't agree with the comments, you don't necessarily have to make changes. Just like paper review, just list what the comment was and why you don't agree or what your alternate change will be. When you submit a new draft, that moment is a great time to, in writing:

1) explain major changes
2) explain changes you won't make and why
3) explain compromise changes
4) *answer questions* that I asked in the margins (I think we discussed this, and you agreed you would do so, but the new issue requesting my review didn't answer any questions.... )

**Comment by jbae11** [comment]
@katyhuff 

[here](https://docs.google.com/document/d/1ZHGL3ucQMbeREFkL2_IVthtl1GIvNIjir4pBZz3s0CI/edit) is the google doc with answers to questions and comments. If there is an easier format for you to read, please let me know. Thanks.
